// Generated by gencpp from file ilk_paket/kelimeSayaciRequest.msg
// DO NOT EDIT!


#ifndef ILK_PAKET_MESSAGE_KELIMESAYACIREQUEST_H
#define ILK_PAKET_MESSAGE_KELIMESAYACIREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ilk_paket
{
template <class ContainerAllocator>
struct kelimeSayaciRequest_
{
  typedef kelimeSayaciRequest_<ContainerAllocator> Type;

  kelimeSayaciRequest_()
    : kelimeler()  {
    }
  kelimeSayaciRequest_(const ContainerAllocator& _alloc)
    : kelimeler(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _kelimeler_type;
  _kelimeler_type kelimeler;





  typedef boost::shared_ptr< ::ilk_paket::kelimeSayaciRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ilk_paket::kelimeSayaciRequest_<ContainerAllocator> const> ConstPtr;

}; // struct kelimeSayaciRequest_

typedef ::ilk_paket::kelimeSayaciRequest_<std::allocator<void> > kelimeSayaciRequest;

typedef boost::shared_ptr< ::ilk_paket::kelimeSayaciRequest > kelimeSayaciRequestPtr;
typedef boost::shared_ptr< ::ilk_paket::kelimeSayaciRequest const> kelimeSayaciRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ilk_paket::kelimeSayaciRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ilk_paket::kelimeSayaciRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ilk_paket::kelimeSayaciRequest_<ContainerAllocator1> & lhs, const ::ilk_paket::kelimeSayaciRequest_<ContainerAllocator2> & rhs)
{
  return lhs.kelimeler == rhs.kelimeler;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ilk_paket::kelimeSayaciRequest_<ContainerAllocator1> & lhs, const ::ilk_paket::kelimeSayaciRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ilk_paket

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ilk_paket::kelimeSayaciRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ilk_paket::kelimeSayaciRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ilk_paket::kelimeSayaciRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ilk_paket::kelimeSayaciRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ilk_paket::kelimeSayaciRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ilk_paket::kelimeSayaciRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ilk_paket::kelimeSayaciRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9a1faabfc5040cbb654dd6b25c17425b";
  }

  static const char* value(const ::ilk_paket::kelimeSayaciRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9a1faabfc5040cbbULL;
  static const uint64_t static_value2 = 0x654dd6b25c17425bULL;
};

template<class ContainerAllocator>
struct DataType< ::ilk_paket::kelimeSayaciRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ilk_paket/kelimeSayaciRequest";
  }

  static const char* value(const ::ilk_paket::kelimeSayaciRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ilk_paket::kelimeSayaciRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string kelimeler\n"
;
  }

  static const char* value(const ::ilk_paket::kelimeSayaciRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ilk_paket::kelimeSayaciRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.kelimeler);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct kelimeSayaciRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ilk_paket::kelimeSayaciRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ilk_paket::kelimeSayaciRequest_<ContainerAllocator>& v)
  {
    s << indent << "kelimeler: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.kelimeler);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ILK_PAKET_MESSAGE_KELIMESAYACIREQUEST_H
