// Generated by gencpp from file ilk_paket/toplam.msg
// DO NOT EDIT!


#ifndef ILK_PAKET_MESSAGE_TOPLAM_H
#define ILK_PAKET_MESSAGE_TOPLAM_H

#include <ros/service_traits.h>


#include <ilk_paket/toplamRequest.h>
#include <ilk_paket/toplamResponse.h>


namespace ilk_paket
{

struct toplam
{

typedef toplamRequest Request;
typedef toplamResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct toplam
} // namespace ilk_paket


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ilk_paket::toplam > {
  static const char* value()
  {
    return "fe8aac20b87d53f504c5864a0ca7afb7";
  }

  static const char* value(const ::ilk_paket::toplam&) { return value(); }
};

template<>
struct DataType< ::ilk_paket::toplam > {
  static const char* value()
  {
    return "ilk_paket/toplam";
  }

  static const char* value(const ::ilk_paket::toplam&) { return value(); }
};


// service_traits::MD5Sum< ::ilk_paket::toplamRequest> should match
// service_traits::MD5Sum< ::ilk_paket::toplam >
template<>
struct MD5Sum< ::ilk_paket::toplamRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ilk_paket::toplam >::value();
  }
  static const char* value(const ::ilk_paket::toplamRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ilk_paket::toplamRequest> should match
// service_traits::DataType< ::ilk_paket::toplam >
template<>
struct DataType< ::ilk_paket::toplamRequest>
{
  static const char* value()
  {
    return DataType< ::ilk_paket::toplam >::value();
  }
  static const char* value(const ::ilk_paket::toplamRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ilk_paket::toplamResponse> should match
// service_traits::MD5Sum< ::ilk_paket::toplam >
template<>
struct MD5Sum< ::ilk_paket::toplamResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ilk_paket::toplam >::value();
  }
  static const char* value(const ::ilk_paket::toplamResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ilk_paket::toplamResponse> should match
// service_traits::DataType< ::ilk_paket::toplam >
template<>
struct DataType< ::ilk_paket::toplamResponse>
{
  static const char* value()
  {
    return DataType< ::ilk_paket::toplam >::value();
  }
  static const char* value(const ::ilk_paket::toplamResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ILK_PAKET_MESSAGE_TOPLAM_H
