name: tutorial-project # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: tutorial project of snap test # 79 char long summary
description: |
 tutorial project of snap test.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  workspace:
    plugin: catkin
    source: .
    build-packages: [g++, make,ros-noetic-catkin]
    source-branch: noetic-devel
    catkin-packages: [ilk_paket]
    

apps:
  starter:
    command: opt/ros/noetic/bin/roslaunch ilk_paket test.launch
    plugs: [network,network-bind]
    extensions: [ros1-noetic]
    
  
